#!/bin/sh
curl -o PFAS.pdb https://alphafold.ebi.ac.uk/files/AF-O15067-F1-model_v1.pdb
curl -o PFAS.pdb https://alphafold.ebi.ac.uk/files/AF-O15067-F1-model_v2.pdb
curl -o PFAS.pdb https://alphafold.ebi.ac.uk/files/AF-O15067-F1-model_v3.pdb
curl -o PFAS.pdb https://alphafold.ebi.ac.uk/files/AF-O15067-F1-model_v4.pdb
curl -o PFAS.pdb https://alphafold.ebi.ac.uk/files/AF-O15067-F1-model_v5.pdb
curl -o PGM3.pdb https://alphafold.ebi.ac.uk/files/AF-O95394-F1-model_v1.pdb
curl -o PGM3.pdb https://alphafold.ebi.ac.uk/files/AF-O95394-F1-model_v2.pdb
curl -o PGM3.pdb https://alphafold.ebi.ac.uk/files/AF-O95394-F1-model_v3.pdb
curl -o PGM3.pdb https://alphafold.ebi.ac.uk/files/AF-O95394-F1-model_v4.pdb
curl -o PGM3.pdb https://alphafold.ebi.ac.uk/files/AF-O95394-F1-model_v5.pdb
curl -o PIM2.pdb https://alphafold.ebi.ac.uk/files/AF-Q9P1W9-F1-model_v1.pdb
curl -o PIM2.pdb https://alphafold.ebi.ac.uk/files/AF-Q9P1W9-F1-model_v2.pdb
curl -o PIM2.pdb https://alphafold.ebi.ac.uk/files/AF-Q9P1W9-F1-model_v3.pdb
curl -o PIM2.pdb https://alphafold.ebi.ac.uk/files/AF-Q9P1W9-F1-model_v4.pdb
curl -o PIM2.pdb https://alphafold.ebi.ac.uk/files/AF-Q9P1W9-F1-model_v5.pdb
curl -o PMM2.pdb https://alphafold.ebi.ac.uk/files/AF-O15305-F1-model_v1.pdb
curl -o PMM2.pdb https://alphafold.ebi.ac.uk/files/AF-O15305-F1-model_v2.pdb
curl -o PMM2.pdb https://alphafold.ebi.ac.uk/files/AF-O15305-F1-model_v3.pdb
curl -o PMM2.pdb https://alphafold.ebi.ac.uk/files/AF-O15305-F1-model_v4.pdb
curl -o PMM2.pdb https://alphafold.ebi.ac.uk/files/AF-O15305-F1-model_v5.pdb
curl -o POU2AF1.pdb https://alphafold.ebi.ac.uk/files/AF-Q16633-F1-model_v1.pdb
curl -o POU2AF1.pdb https://alphafold.ebi.ac.uk/files/AF-Q16633-F1-model_v2.pdb
curl -o POU2AF1.pdb https://alphafold.ebi.ac.uk/files/AF-Q16633-F1-model_v3.pdb
curl -o POU2AF1.pdb https://alphafold.ebi.ac.uk/files/AF-Q16633-F1-model_v4.pdb
curl -o POU2AF1.pdb https://alphafold.ebi.ac.uk/files/AF-Q16633-F1-model_v5.pdb
curl -o PPCDC.pdb https://alphafold.ebi.ac.uk/files/AF-Q96CD2-F1-model_v1.pdb
curl -o PPCDC.pdb https://alphafold.ebi.ac.uk/files/AF-Q96CD2-F1-model_v2.pdb
curl -o PPCDC.pdb https://alphafold.ebi.ac.uk/files/AF-Q96CD2-F1-model_v3.pdb
curl -o PPCDC.pdb https://alphafold.ebi.ac.uk/files/AF-Q96CD2-F1-model_v4.pdb
curl -o PPCDC.pdb https://alphafold.ebi.ac.uk/files/AF-Q96CD2-F1-model_v5.pdb
curl -o PRDM1.pdb https://alphafold.ebi.ac.uk/files/AF-O75626-F1-model_v1.pdb
curl -o PRDM1.pdb https://alphafold.ebi.ac.uk/files/AF-O75626-F1-model_v2.pdb
curl -o PRDM1.pdb https://alphafold.ebi.ac.uk/files/AF-O75626-F1-model_v3.pdb
curl -o PRDM1.pdb https://alphafold.ebi.ac.uk/files/AF-O75626-F1-model_v4.pdb
curl -o PRDM1.pdb https://alphafold.ebi.ac.uk/files/AF-O75626-F1-model_v5.pdb
curl -o ZEB1.pdb https://alphafold.ebi.ac.uk/files/AF-P37275-F1-model_v1.pdb
curl -o ZEB1.pdb https://alphafold.ebi.ac.uk/files/AF-P37275-F1-model_v2.pdb
curl -o ZEB1.pdb https://alphafold.ebi.ac.uk/files/AF-P37275-F1-model_v3.pdb
curl -o ZEB1.pdb https://alphafold.ebi.ac.uk/files/AF-P37275-F1-model_v4.pdb
curl -o ZEB1.pdb https://alphafold.ebi.ac.uk/files/AF-P37275-F1-model_v5.pdb
curl -o ZNF296.pdb https://alphafold.ebi.ac.uk/files/AF-Q8WUU4-F1-model_v1.pdb
curl -o ZNF296.pdb https://alphafold.ebi.ac.uk/files/AF-Q8WUU4-F1-model_v2.pdb
curl -o ZNF296.pdb https://alphafold.ebi.ac.uk/files/AF-Q8WUU4-F1-model_v3.pdb
curl -o ZNF296.pdb https://alphafold.ebi.ac.uk/files/AF-Q8WUU4-F1-model_v4.pdb
curl -o ZNF296.pdb https://alphafold.ebi.ac.uk/files/AF-Q8WUU4-F1-model_v5.pdb
curl -o ZNF592.pdb https://alphafold.ebi.ac.uk/files/AF-Q92610-F1-model_v1.pdb
curl -o ZNF592.pdb https://alphafold.ebi.ac.uk/files/AF-Q92610-F1-model_v2.pdb
curl -o ZNF592.pdb https://alphafold.ebi.ac.uk/files/AF-Q92610-F1-model_v3.pdb
curl -o ZNF592.pdb https://alphafold.ebi.ac.uk/files/AF-Q92610-F1-model_v4.pdb
curl -o ZNF592.pdb https://alphafold.ebi.ac.uk/files/AF-Q92610-F1-model_v5.pdb
